### ISSUE TITLE
MacOS: no such file or directory, open '-c/.cookies.json'

### ISSUE THREAD

**Issue by itsrxns** [Godzil/Crunchy#112]
**Describe the bug**
I can't run Crunchy > no such file or directory, open '-c/.cookies.json'

**Expected behavior**
Downloading series

**Screenshots**
crunchy -u ID -p PASSWORD http://www.crunchyroll.com/fairy-tail 
 * INFO : Crunchy version 1.5.0
fs.js:127
    throw err;
    ^
Error: ENOENT: no such file or directory, open '-c/.cookies.json'
    at Object.openSync (fs.js:448:3)
    at loadCookies (/usr/local/lib/node_modules/crunchy/dist/my_request.js:132:25)
    at Object.get (/usr/local/lib/node_modules/crunchy/dist/my_request.js:153:9)
    at pageScrape (/usr/local/lib/node_modules/crunchy/dist/series.js:145:20)
    at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/crunchy/dist/series.js:35:9)
    at ReadFileContext.callback (/usr/local/lib/node_modules/crunchy/node_modules/graceful-fs/graceful-fs.js:115:16)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:247:13) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '-c/.cookies.json'
}

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: MacOS Mojave 10.14.5
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): Italy
 - Serie you get a problem with (and specify which episode if it is specific to one): Fairy Tail (test)
 - The command line you are running Crunchy with: crunchy -u ID -p PASSWORD http://www.crunchyroll.com/fairy-tail 
 - The message Crunchy is giving you, if any: 

**Please be careful to remove your real account login and password if they appear!**

**Additional context**

_Also don't hesitate to add labels you feel apropriate on your report._
_Please don't edit logs if you are adding them, apart from removing sensitive informations like login/password_

**Comment by Godzil** [comment]
Hmm weird...

Can you show me the content of your config.json file?
Be careful to not show your CR login/password from it.
Also what is your current path?

Going to look a bit at it and come back after
