### ISSUE TITLE
"Authentication failed"

### ISSUE THREAD

**Issue by jakepbrown27** [Godzil/Crunchy#12]
Getting an authentication error as of late, not sure but I wonder if it is related to crunchyroll's implementation of cloudflare? Not sure if I recall seeing it before - error goes as such:

crunchy http://www.crunchyroll.com/brotherhood-final-fantasy-xv -u [username]  -p [password] 
Error: Authentication failed:
    at Request._callback (***\AppData\Roaming\npm\node_modules\crunchy\dist\request.js:100:33)
    at Request.self.callback (***\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:344:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (***\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1239:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (***\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1187:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

I did make sure that I was using the correct username and password. Any ideas?

**Comment by wookiee** [comment]
I've gotten this also for a handful of series (not all):

```
Freyja:~ mikey$ crunchy --output ~/Movies/Anime -u ***** -p ***** http://www.crunchyroll.com/sound-euphonium
Error: Authentication failed: 
    at Request._callback (/usr/local/lib/node_modules/crunchy/dist/request.js:100:33)
    at Request.self.callback (/usr/local/lib/node_modules/crunchy/node_modules/request/request.js:344:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/crunchy/node_modules/request/request.js:1239:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/crunchy/node_modules/request/request.js:1187:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by Godzil** [comment]
I haven't been able to use Crunchy for a couple of week due to network issues, but I will look into that, that's not normal, maybe another change in the website layout? .. :/

**Comment by wookiee** [comment]
happy to help with testing when you get to it if you like

**Comment by jpmckinney** [comment]
`https://www.crunchyroll.com/login` first loads a Cloudflare page, then eventually loads the page.

**Comment by majewskim** [comment]
Hey
I had a look yesterday and it's pretty smart how they did it.
I have a solution and I'll try to finish a prototype today so we can test it out.

**Comment by clienthax** [comment]
Would it not be easier to use this for the login, strips out a lot of form parsing.

https://www.crunchyroll.com/?a=formhandler&formname=RpcApiUser_Login&name=%username%&password=%password% 

Redirects to the main page after.

**Comment by majewskim** [comment]
Of course the simplest solution worked like a charm :)
Thanks @clienthax 
I'll do the PR today.

**Comment by Godzil** [comment]
Thanks for your work, I will look at your PR when it is submitted :)

**Comment by majewskim** [comment]
I just did it @Godzil

**Comment by clienthax** [comment]
Thanks @majewskim works perfectly my end.
I suck at JavaScript/Typescript but am great at workarounds ;)

**Comment by majewskim** [comment]
glad to hear @clienthax :)

**Comment by Godzil** [comment]
Thanks for the fix, version 1.1.12 is currently pushing to NPM.

But please next time start your branch from the master of my branch it will make diff simpler :)

**Comment by majewskim** [comment]
Hey
I tried, but it wouldn't let me, saying I have no permissions, so I had to
fork it and did it on mine :/
You can add me to the contributors and then I can do stuff like that I
think.

**Comment by Godzil** [comment]
No worries, that just weird you weren't able to fork this fork.
