### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by JySzE** [Godzil/Crunchy#27]
@Godzil 

`C:\Windows\system32>crunchy --output C:\anime http://www.crunchyroll.com/naruto -u ***** -p *****
 * INFO : You have a premium account! Good!
 * INFO : Checking availability for Naruto
Error: Command failed: "C:\Users\Jacob\AppData\Roaming\npm\node_modules\crunchy\bin\ffmpeg.exe" -i "https://dl.v.vrv.co/evs/assets/0mpglz1x6g5hztu_1514259.mp4/master.m3u8?Policy=ewoiU3RhdGVtZW50IjpbCnsKIlJlc291cmNlIjoiaHR0cHM6Ly9kbC52LnZydi5jby9ldnMvYXNzZXRzLzBtcGdsejF4Nmc1aHp0dV8xNTE0MjU5Lm1wNC9tYXN0ZXIubTN1OCIsCiJDb25kaXRpb24iOnsKIkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkzODM1NDU3fQp9Cn0KXQp9&Signature=qVTQmtNLmw0Dmrpe1bxAZyrRsbJhdRWCue9HDdzhNsyqt0p5w9estHnhETy2AmZeo0U4LsxgAiY5MK6bYMXsDxvWsKjFI~2J~MqlZYayD-rA-HRlfajp-K1se9gTnYZKE29mxYOHDtlWiD3jFjU89ygXKVZD40qW~E1qwmh9nO~qfqJ9drLE4pbaAG23gEOG-qqNQRTsLoERUrB-BchWRcL3GJlat8SfCRaSQR3ZQy507F81Nod85h30YWG9B-ctMo6PuqIwTC9NKBGIhhbGsHS4ZFPCk9gf5XC4fqq0r8k1upwrw7ITMOglBch8XH~fHMNM6oSrSD8bQXGHIeb-cg__&Key-Pair-Id=DLVR" -c copy -bsf:a aac_adtstoasc "C:\anime\Naruto\Naruto - s01e01 - [CrunchyRoll].mp4"
ffmpeg version N-81328-gceab04f Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 51.102 / 57. 51.102
  libavformat    57. 46.101 / 57. 46.101
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 51.100 /  6. 51.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
https://dl.v.vrv.co/evs/assets/0mpglz1x6g5hztu_1514259.mp4/master.m3u8?Policy=ewoiU3RhdGVtZW50IjpbCnsKIlJlc291cmNlIjoiaHR0cHM6Ly9kbC52LnZydi5jby9ldnMvYXNzZXRzLzBtcGdsejF4Nmc1aHp0dV8xNTE0MjU5Lm1wNC9tYXN0ZXIubTN1OCIsCiJDb25kaXRpb24iOnsKIkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkzODM1NDU3fQp9Cn0KXQp9&Signature=qVTQmtNLmw0Dmrpe1bxAZyrRsbJhdRWCue9HDdzhNsyqt0p5w9estHnhETy2AmZeo0U4LsxgAiY5MK6bYMXsDxvWsKjFI~2J~MqlZYayD-rA-HRlfajp-K1se9gTnYZKE29mxYOHDtlWiD3jFjU89ygXKVZD40qW~E1qwmh9nO~qfqJ9drLE4pbaAG23gEOG-qqNQRTsLoERUrB-BchWRcL3GJlat8SfCRaSQR3ZQy507F81Nod85h30YWG9B-ctMo6PuqIwTC9NKBGIhhbGsHS4ZFPCk9gf5XC4fqq0r8k1upwrw7ITMOglBch8XH~fHMNM6oSrSD8bQXGHIeb-cg__&Key-Pair-Id=DLVR: Unknown error

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)`

**Comment by JySzE** [comment]
` * INFO : You have a premium account! Good!
 * INFO : Checking availability for Naruto
Error: Command failed: "C:\Users\Jacob\AppData\Roaming\npm\node_modules\crunchy\bin\ffmpeg.exe" -i "https://dl.v.vrv.co/evs/assets/0mpglz1x6g5hztu_1514259.mp4/master.m3u8?Policy=ewoiU3RhdGVtZW50IjpbCnsKIlJlc291cmNlIjoiaHR0cHM6Ly9kbC52LnZydi5jby9ldnMvYXNzZXRzLzBtcGdsejF4Nmc1aHp0dV8xNTE0MjU5Lm1wNC9tYXN0ZXIubTN1OCIsCiJDb25kaXRpb24iOnsKIkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNDkzODM1NDU3fQp9Cn0KXQp9&Signature=qVTQmtNLmw0Dmrpe1bxAZyrRsbJhdRWCue9HDdzhNsyqt0p5w9estHnhETy2AmZeo0U4LsxgAiY5MK6bYMXsDxvWsKjFI~2J~MqlZYayD-rA-HRlfajp-K1se9gTnYZKE29mxYOHDtlWiD3jFjU89ygXKVZD40qW~E1qwmh9nO~qfqJ9drLE4pbaAG23gEOG-qqNQRTsLoERUrB-BchWRcL3GJlat8SfCRaSQR3ZQy507F81Nod85h30YWG9B-ctMo6PuqIwTC9NKBGIhhbGsHS4ZFPCk9gf5XC4fqq0r8k1upwrw7ITMOglBch8XH~fHMNM6oSrSD8bQXGHIeb-cg__&Key-Pair-Id=DLVR" -c copy -bsf:a aac_adtstoasc "C:\anime\Naruto\Naruto - s01e01 - [CrunchyRoll].mp4"

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by JySzE** [comment]
Attempted to download Fairy tail, Naruto, Naruto Shippuden, Bleach, DBS. None are working.

**Comment by JySzE** [comment]
Fixed, i went to the link highlighted in my last post and it showed what CR server i was connected to, i turned on my vpn connected to somewhere farther away in the US and now i am forced to connect to a different CR server and the issue went away. Thanks.
