### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by Jfigs101** [Godzil/Crunchy#39]
attempting to download and receive the following message: 

/usr/local/lib/node_modules/crunchy/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/crunchy/dist/series.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

crunchy command: 

crunchy -u *** -p *** -o /mnt/d/Anime -e 783 http://www.crunchyroll.com/one-piece

**Comment by Godzil** [comment]
With the release version (on npm) and not the current dev on GitHub?

**Comment by Jfigs101** [comment]
Release version

node: 0.10.25
npm 1.3.10

**Comment by Jfigs101** [comment]
any recommendations to get this up and running? If the NPM version isn't good, is current dev working? If so, can I get some rough steps on how to install on ubuntu?

**Comment by Godzil** [comment]
Well as the readme says "NodeJS >= 5.x (http://nodejs.org/)" (I'm using version 7.10.0 locally)

I don't really get the nodejs versioning scheme, but as far as I know 0.10 is a fairly old branch
