### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by macravin** [Godzil/Crunchy#42]
Got the following error trying to download from [http://www.crunchyroll.com/owarimonogatari](//www.crunchyroll.com/owarimonogatari). This series did not work with the older @Deathspike version either. Any ideas? Anyone have similar issues?

```
/usr/local/lib/node_modules/crunchy/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/crunchy/dist/series.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by Godzil** [comment]
What is your version of node? Are you using the version from NPM or are you trying to build it?

**Comment by macravin** [comment]
This was the npm version. I'll post my version of node when I get back to
my system tonight.

**Comment by Godzil** [comment]
Npm can’t enforce a minimum version of node, which is a really stupid idea. Not really a Crunchy issue and nothing that can easily be done.
