### ISSUE TITLE
ERROR: Auth failed!

### ISSUE THREAD

**Issue by KurumoAkane** [Godzil/Crunchy#48]
Hi, i'll trying this fork, but it gave me auth error..
My account is Premium.. But it not work..
I have tried bot _--user_ / _--pass_ and _-u_ / _-p_... But still not work..

## Linux ##
```
kurumo@mypc:~$ crunchy -u USER -p PASSWORD http://www.crunchyroll.com/restaurant-to-another-world
Error: Authentication failed: 
    at /usr/lib/node_modules/crunchy/dist/my_request.js:114:33
    at giveResults (/usr/lib/node_modules/crunchy/node_modules/cloudscraper/index.js:244:5)
    at Request._callback (/usr/lib/node_modules/crunchy/node_modules/cloudscraper/index.js:109:7)
    at Request.self.callback (/usr/lib/node_modules/crunchy/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/crunchy/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/crunchy/node_modules/request/request.js:1085:12)
```
## Windows ##
```
C:\Users\Kurumo>crunchy -u USER-p PASSWORD https://www.crunchyroll.com/restaurant-to-another-world
Error: Authentication failed:
    at C:\Users\Kurumo\AppData\Roaming\npm\node_modules\crunchy\dist\my_request.js:114:33
    at giveResults (C:\Users\Kurumo\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:244:5)
    at Request._callback (C:\Users\Kurumo\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:109:7)
    at Request.self.callback (C:\Users\Kurumo\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Kurumo\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Kurumo\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1085:12)
```
I've tried on both **Windows 8.1**, **Linux Mint 18.2** and **Debian 9**, with **NodeJS 6.11.2** and **NPM 3.10.10** on all systems... Obv **RTMPDump**, **FFMPEG** and **MKVTOOLNIX** are installed! I have tested also with different anime..

Can be the case that CR is using the **CloudFlare** maximum protection?!

**Comment by Godzil** [comment]
I don't have any problems here, do you put single or double quotes around your password?

**Comment by Godzil** [comment]
No comment since, I consider it as solved.

It you still have any issue, please reopen.
