### ISSUE TITLE
A parser can't parse something

### ISSUE THREAD

**Issue by Cubesoup** [Godzil/Crunchy#57]
I've tried to download a few different series (older, newer), and individual episodes. The result is always some version of this:

crunchy -u my-username -p my-password https://crunchyroll.com/the-ancient-magus-bride -e 1

 * INFO : You have a premium account! Good!
 * INFO : Checking availability for The Ancient Magus' Bride
TypeError: Cannot read property 'subtitle' of undefined
    at /usr/lib/node_modules/crunchy/dist/episode.js:238:69
    at Parser.<anonymous> (/usr/lib/node_modules/crunchy/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:160:13)
    at SAXParser.onclosetag (/usr/lib/node_modules/crunchy/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/lib/node_modules/crunchy/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/crunchy/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/crunchy/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/crunchy/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/crunchy/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/usr/lib/node_modules/crunchy/node_modules/xml2js/lib/parser.js:5:59)

I'm interested to know if someone can replicate the problem.

**Comment by Godzil** [comment]
Hmmm there are sometimes some transient error with CR website, I don’t have any issues right now and can’t reproduce..

Have you tried again since you reported?

**Comment by Jimm1432** [comment]
try setting your subs to english in the account settings?

**Comment by Cubesoup** [comment]
I had tried setting the default language to English in my account settings, thinking it might be a character encoding problem, but it didn't work. Also haven't tried to reproduce bug since. youtube-dl works on crunchyroll, and I've been using that instead.
