### ISSUE TITLE
 Authentication failed

### ISSUE THREAD

**Issue by Jimm1432** [Godzil/Crunchy#59]
Won't use my login/password, fails for any premium eps.  
Crunchy updated there cloudflare?

`Error: Authentication failed:
    at C:\Users\user\AppData\Roaming\npm\node_modules\crunchy\dist\my_request.js:114:33
    at giveResults (C:\Users\user\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:244:5)
    at Request._callback (C:\Users\user\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:109:7)
    at Request.self.callback (C:\Users\user\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)`

**Comment by JabronieMan** [comment]
I'm seeing a similar issue.

Error: Authentication failed:
    at /usr/local/lib/node_modules/crunchy/dist/request.js:113:33
    at giveResults (/usr/local/lib/node_modules/crunchy/node_modules/cloudscraper/index.js:244:5)
    at Request._callback (/usr/local/lib/node_modules/crunchy/node_modules/cloudscraper/index.js:109:7)
    at Request.self.callback (/usr/local/lib/node_modules/crunchy/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/crunchy/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/crunchy/node_modules/request/request.js:1091:12)

**Comment by Godzil** [comment]
I saw that a couple of days ago, still not sure what happening there.

What I can say is that it is transient, wait a bit and retry it will work.

**Comment by Maizumi11** [comment]
I'm experiencing the same issue. I tried to dig in a bit and there appears to be some problem with the redirection through Cloudflare. There is some recent update of cloudscraper so maybe it could solve the problem.

When playing with the issue it "miraculously" worked like in 1 out of 20 tries.

**Comment by Godzil** [comment]
Oh ohoh..... seems like CR had enable the captcha, now it return "{ errorType: 1 }" which is because of the captcha

Crap, not this is not going to be simple to solve if cloudscrape is not supporting it :/

**Comment by Maizumi11** [comment]
Thank you for the investigation of the issue. At least it's clear what happened.

**Comment by Maizumi11** [comment]
Unfortunately, I wasn't able to get it work. Two times I saw "{ errorType: 1 }" error and three times the exception posted above.

**Comment by ilukasschneider** [comment]
@Godzil can you give an estamation in regards of when 1.3 is going to be online?

**Comment by Godzil** [comment]
I've done some changes, nothing magic, I still not sure what is failing on CR side making Crunchy to react this way. What I've done is to make the tool a bit more command line friendly by returning proper value when it works or fail.

I've also added a bash shell script that is installed along the crunchy command line tool. The name is straightforward _crunchy.sh_ and take the same parameters. So if you run crunchy, get an error, just re-run the same command with `crunchy.sh` instead, and it will run retrying until it either work or fail 20 times. (There is a small delay between each retry to not hammer CR website.)

**Comment by Maizumi11** [comment]
Thank you for the changes. I have updated to 1.2.1. On the 6th try the download started. Before that the "{ errorType: 1 }" was returned. I have tried it manually since I can't run bash on Windows.

It's good to know it works after multiple retries.

Btw, there seems to be an extra parameter "-u" in the bash script.

**Comment by Godzil** [comment]
> Btw, there seems to be an extra parameter "-u" in the bash script.

oops :D Thanks to have spotted that.
Fixed in release v1.2.2
