### ISSUE TITLE
Some episodes unmergeable.

### ISSUE THREAD

**Issue by wookiee** [Godzil/Crunchy#65]
For Love Live Sunshine, crunchy fails to merge the subtitles  at episode 7. Eps 1-6 work fine.

![screen shot 2018-06-01 at 7 20 03 am](https://user-images.githubusercontent.com/1214535/40839393-5b924684-6570-11e8-8457-11b743a9fac2.png)

**Comment by wookiee** [comment]
Upon further investigation, the .ass file is for an episode in the wrong season. It's downloaded the video for s1e7 but the subtitle track for s2e7. Interesting.

**Comment by wookiee** [comment]
Think I found it. The subtitles file has an erroneous reference to something at the 25m mark, instead of the 23m mark, which is past the end of the video. mkvmerge seems to die trying to build an mkv with timestamps past the end of the video, and builds a corrupt mkv that's too long. Not sure there's anything Crunchy can do about this.

**Comment by wookiee** [comment]
But fixing the timestamp and re-running the `mkvmerge` fixes it. ¯\_(ツ)_/¯ Feel free to close this thread if it's irrelevant to you.

**Comment by Godzil** [comment]
Which version of mkvmerge are you using? never got a crash for theses things; but got videos with improper timing. 

I do have some ideas on how to solve it, but would need to take time to clear it.

Could you please put here when you find them episodes that cause a problem?

Thanks :)

**Comment by wookiee** [comment]
Sure thing! Here's my tools versions:

    mkvmerge v23.0.0 ('The Bride Said No') 64-bit
    npm 6.1.0
    node v10.3.0 (installed via homebrew)
    crunchy 1.2.2

…here's a copypasta of the error output:

    Error: Command failed: mkvmerge -o "/Users/mikey/Movies/Anime/Love Live! Sunshine!!/Love Live! Sunshine!! - s01e07 - [CrunchyRoll]-1.mkv" "/Users/mikey/Movies/Anime/Love Live! Sunshine!!/Love Live! Sunshine!! - s01e07 - [CrunchyRoll]-1.mp4" "/Users/mikey/Movies/Anime/Love Live! Sunshine!!/Love Live! Sunshine!! - s01e07 - [CrunchyRoll]-1.ass"

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

…and the URL of the episode with the corrupted subtitle:

http://www.crunchyroll.com/love-live-sunshine/episode-7-tokyo-715947

In case you're curious, the error is on line 408 of the subtitle file, where a title is set to end at 0:25:40.07 instead of 0:23:…, putting it past the end of the episode. Whoops.
