### ISSUE TITLE
index callback gives null error

### ISSUE THREAD

**Issue by polyDog** [Godzil/Crunchy#70]
crunchy has worked great for a long time -- really nice tool - thank you!

**Describe the bug**
a week or two after May 26th have consistently run into this.  crunchy no longer runs.  looks like a null was encountered trying to read a property 'stack'

**Expected behavior**
proceed to fetch episode(s)

**Screenshots**
screenshot added

**Please fill theses informations:**

 - **OS**: [Windows 10]
 - **[ x ]** I'm using the latest version of Crunchy
 - **tested with:** http://www.crunchyroll.com/hundred
 - **The command line you are running Crunchy with:** 'crunchy http://www.crunchyroll.com/hundred' 
 - The message Crunchy is giving you, if any:

++++++++++++++++++++++++++++++++++++++++++++++++
F:\content\crunchy>crunchy http://www.crunchyroll.com/hundred
 * INFO : Crunchy version 1.3.1
 * WARN : Retrying to fetch episodes 5 / 5
 * WARN : Retrying to fetch episodes 4 / 5
 * WARN : Retrying to fetch episodes 3 / 5
 * WARN : Retrying to fetch episodes 2 / 5
 * WARN : Retrying to fetch episodes 1 / 5
C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\dist\batch.js:50
                        console.error(err.stack || err);
                                          ^

TypeError: Cannot read property 'stack' of null
    at C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\dist\batch.js:50:43
    at C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\dist\series.js:37:24
    at C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\dist\series.js:138:24
    at C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\dist\my_request.js:69:24
    at Request._callback (C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\node_modules\cloudscraper\index.js:90:14)
    at self.callback (C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\w\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketOnEnd (_http_client.js:423:9)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
++++++++++++++++++++++++++++++++++++++++++++++++

**Additional context**

- **npm version** 5.6.0

- **node version** v8.11.3

- crunchy is unable to dl anything - just returns similar to above stack trace

-  **this issue began sometime after May 26**

- have been watching crunchy issues but no one else is reporting so maybe I am the only one experiencing an issue

-  have recently 'reset' windows -- same error message before and after windows reset

![crunchy01](https://user-images.githubusercontent.com/40610373/41933309-4ed7fef8-7938-11e8-9601-0b3789c74a48.PNG)

**Comment by Godzil** [comment]
Ok there is a bug in Crunchy when it try to display the real error, I do have a fix fox it but haven't release a new version, was not expecting someone to run on it that soon.

I will push it and try on my side to see if I get error with that anime, and if you have still the same error, please give me the new error displayed.

Sorry for the inconvenience

**Comment by polyDog** [comment]
no inconvenience here expressed or implied :)

multiple titles tested with specific episodes and/or just the general page start page -- seems to give the same result.  

in this case was just 'crunchy http://www.crunchyroll.com/hundred' which was picked at random.  this command  should be pulling the 1st one by default if I understand correctly

will watch here when I should test --- would just be pulling the latest update right?

(also I've never contributed before -- how does one get involved?  Is there any way to communicate privately?)

**Comment by Godzil** [comment]
Yes I've updated on npm yesterday, please try to update and tell me what it return, it, at least, should not crash anymore 🤞

**Comment by polyDog** [comment]
OK no crash! -- here is what was returned:

![image](https://user-images.githubusercontent.com/40610373/42070924-70d5b3b6-7b0d-11e8-9382-e437a408cb49.png)

**Comment by Godzil** [comment]
Oh crap... whybthis thing is so useless....

But ok it seems that it is not able to list episodes from that series, can you confirm that you see them on CR? Does you CR is in English?

**Comment by polyDog** [comment]
Yes can see them when visiting CR from a browser (screenshot below)
Yes English episode names

Am on a tight deadline for a project at the moment or I would setup and try to debug this.  I have done a bit of node/js  

Is there any way for you and I to communicate privately?  Or is open forum the only way?

Pic from browser:
![hundred](https://user-images.githubusercontent.com/40610373/42115903-c311298e-7ba9-11e8-982d-9f783c2667f4.png)

**Comment by polyDog** [comment]
update:

tested w/VPN to different area -- same problem still exists. 
tested on new Ubuntu image --- same problem still exists.

**Comment by Godzil** [comment]
There must be something that make Crunchy unable to parse the page, I don't understand it works fine here (ans probably for lots of other peoples..)

**Comment by polyDog** [comment]
Ah OK -- I wish I knew how I assist you better in triage! -- here is some more info:

output from console below -- output from debug attached
++++++++++++++++++++++++++++++++++++++

 * INFO : Crunchy version 1.3.4
 * WARN : Retrying to fetch episodes list from5 / 5
 * WARN : Retrying to fetch episodes list from4 / 5
 * WARN : Retrying to fetch episodes list from3 / 5
 * WARN : Retrying to fetch episodes list from2 / 5
 * WARN : Retrying to fetch episodes list from1 / 5
{ errorType: 0,
  error: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' } }
 * ERROR: Cannot get episodes from "http://www.crunchyroll.com/hundred", please rerun later
Done!
[debug.txt](https://github.com/Godzil/Crunchy/files/2195495/debug.txt)

**Comment by Godzil** [comment]
Ok, could you please run again with 1.3.5 and send the debug.txt file (you can zip it as it may be big) to

crunchy-debug at godzil dot net

Thanks

You can attach here too, but I can't guaranty that it may not contain some personal information (login/password should not appear but as there are dump of CR pages; I can't guaranty on what they will contain.)
