### ISSUE TITLE
Cannot Download Episodes With Newest Version (1.3.7) Edit: Maybe Solved? Wifi Issue

### ISSUE THREAD

**Issue by barthole** [Godzil/Crunchy#82]
Description of bug:
Seems to be that Crunchy version 1.3.7 is broken on some linux systems (at least Fedora). Tried to download episodes at different times both today and the day before but the same issue persists so it doesn't seem to be a problem with CR. Any time I try to download episodes I get the same output error in the terminal. Happens on any series I try as well. Confirmed error on Overlord, Re_ZERO, Fairytail, and Darling in the Franxx. Regardless if I batch download or try to download specific episodes. Has no problem downloading the subtitle tracks, but seems to have difficulties with video. Weird, because the first time I used 1.3.7 the first episode I downloaded (Re_ZERO ep. 5) was successful and worked without a hitch.

Expected Behavior:
Expected to be able to use crunchy as the awesome tool that it is. Expected to be on an anime binge in my room that doesn't have Wi-Fi, but oh well. If someone knows how to regress to the previous version of crunchy, it'd be worth looking at to see if the issue is also in 1.3.6.

**Screenshots**
Screenshot of error:
![bug](https://user-images.githubusercontent.com/35619135/43362449-ccfcf8b6-9296-11e8-8c3f-98294c1a1c77.png)
Not sure it's entirely necessary, but since this problem is probably linux specific, I figured a neofetch screenshot might have some info that would be beneficial
![brian bash konsole -3- _027](https://user-images.githubusercontent.com/35619135/43362524-a8a576bc-9298-11e8-9758-c4c0747f8f0a.png)

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: Linux (Fedora 27 w/ kernel 4.17.7)
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): United States (Alaska)
 - Series you get a problem with (and specify which episode if it is specific to one): Any and all episodes, all series
 - The command line you are running Crunchy with: terminal -> konsole
 - The message Crunchy is giving you, if any:

[brian@brianlaptop HerpDerpImAHDD]$ crunchy -u <username> -p <password> -r 720 --retry 10 http://www.crunchyroll.com/overlord      
 * INFO : Crunchy version 1.3.7
 * INFO : You have a premium account! Good!
 * INFO : Checking availability for Overlord
 > Overlord - s01e01 - End and Beginning - [CrunchyRoll] : Error...
/usr/lib/node_modules/crunchy/dist/series.js:54
                        if ((reqErr.syscall === 'getaddrinfo') && (reqErr.errno === 'ENOTFOUND')) {
                                    ^

TypeError: Cannot read property 'syscall' of undefined
    at /usr/lib/node_modules/crunchy/dist/series.js:54:37
    at /usr/lib/node_modules/crunchy/dist/series.js:117:20
    at /usr/lib/node_modules/crunchy/dist/episode.js:98:32
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Additional Context: 
In the middle of me taking screenshots and making this bug report, for some reason now crunchy is working for the first time in ~72 hours on my laptop and downloading multiple episodes. I did nothing different. It was the exact same command (crunchy -u <username> -p <password> -r 720 --retry 10 -e 6- http://www.crunchyroll.com/rezero-starting-life-in-another-world-) and I can confirm that in another terminal I just got the exact same error message again. Maybe it could be the fact that I'm on a public network? (McDonald's Wi-Fi) I have no words. I've never experienced anything like this in my life.

**Comment by barthole** [comment]
My guess is that the error is only surfacing because of McDonald's internet policy. Somewhere along the line MD's Wifi is most likely refusing some connections to CR or delaying it to the point where crunchy is unusable. I've had no issues on AT&T's network which is also slower overall (~10 Mbit/s vs MD's 30Mbit/s). Then again there is no concrete evidence for this hypothesis beyond the fact that 1.3.7 works fine on AT&T's network but seems to just break on MD's network.
