### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by elliotrpage** [Godzil/Crunchy#99]
**Describe the bug**
Running crunchy with a valid username and password I get an error about the JSON recieved back from the website. Occurs with multiple episodes of the same series.

**Expected behavior**
The episode to download without any issues.

**Screenshots**

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: Windows 10
 - [X] I'm using the latest version of Crunchy
 - [X] I have a premium accrount on CR
 - [ ] I am using a VPN
 - My region in the world (country or continent): UK
 - Serie you get a problem with (and specify which episode if it is specific to one):
 - The command line you are running Crunchy with: crunchy -u (snip)-p (snip) @https://www.crunchyroll.com/teekyu/episode-30-8-mile-with-senpai-645797 
 - The message Crunchy is giving you, if any: SyntaxError: 
 * INFO : Crunchy version 1.4.5
 * INFO : Trying to fetch from https://www.crunchyroll.com/teekyu/episode-30-8-mile-with-senpai-645797
undefined:1
<br />
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\Elliot\AppData\Roaming\npm\node_modules\crunchy\dist\cli.js:12:30)
    at Request.self.callback (C:\Users\Elliot\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Elliot\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Elliot\AppData\Roaming\npm\node_modules\crunchy\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Please be careful to remove your real account login and password if they appear!**

**Additional context**
Running in command prompt on windows 10, but with and without admin, gives the same error.

**Comment by invisan** [comment]
Same Problem for me.

**Comment by Godzil** [comment]
Oh f**.
No that's on my side, sorry about that, going to check really fast

**Comment by elliotrpage** [comment]
Yep, works! Thanks!
